x-uid_gid: &uid_gid
  USER_ID: ${USER_ID:-1000}
  GROUP_ID: ${GROUP_ID:-1000}

volumes:
  phpmyadmin:
    name: ${APP_NAME:-laravel}_phpmyadmin

services:
  nginx:
    pull_policy: never
    image: ${APP_NAME:-laravel}:nginx
    container_name: ${APP_NAME:-laravel}-nginx
    restart: unless-stopped
    working_dir: /var/www/html
    build:
      context: docker
      dockerfile: nginx/Dockerfile
      args:
        <<: *uid_gid
        NGINX_VERSION: ${NGINX_VERSION:-stable}
    environment:
      APP_DEBUG: ${APP_DEBUG:-true}
      NGINX_HOST: ${NGINX_HOST:-_}
      PHP_MY_ADMIN: ${PHP_MY_ADMIN:-true}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
    volumes:
      - ./docker/nginx/cmd.sh:/usr/local/bin/cmd.sh:ro
      - ./docker/nginx/default.conf:/etc/nginx/templates/default.conf:ro
      - ./:/var/www/html:delegated
      - ./docker/nginx/phpmyadmin.sh:/docker-entrypoint.d/99-phpmyadmin.sh:ro
      - phpmyadmin:/var/www/phpmyadmin
    ports:
      - ${NGINX_PORT:-80}:80
      # - ${NGINX_SSL_PORT:-433}:433
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      start_period: 3s
      interval: 30s
      timeout: 2s
      retries: 3
    depends_on:
      php:
        condition: service_healthy
      db:
        condition: service_healthy
      phpmyadmin:
        condition: service_healthy

  php:
    pull_policy: never
    image: ${APP_NAME:-laravel}:php
    container_name: ${APP_NAME:-laravel}-php
    restart: unless-stopped
    working_dir: /var/www/html
    build:
      context: docker
      dockerfile: php/Dockerfile
      args:
        <<: *uid_gid
        PHP_VERSION: ${PHP_VERSION}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
    environment:
      APP_ENV: ${APP_ENV:-local}
    volumes:
      - ./docker/php/cmd.sh:/usr/local/bin/cmd.sh:ro
      - ./:/var/www/html:delegated
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t 2>&1 | grep -q 'test is successful'"]
      start_period: 3s
      interval: 30s
      timeout: 2s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  db:
    pull_policy: never
    image: ${APP_NAME:-laravel}:${DB_CONNECTION:-sqlite}
    container_name: ${APP_NAME:-laravel}-${DB_CONNECTION:-sqlite}
    restart: unless-stopped
    build: 
      context: docker
      dockerfile: db/${DB_CONNECTION:-sqlite}/Dockerfile
      args:
        <<: *uid_gid
        DB_VERSION: ${DB_VERSION}
    environment:
      APP_NAME: ${APP_NAME:-laravel}
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-laravel}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DB_DATA_DIR:-./docker/db/data}:/var/db
      - ./:/var/www/html:delegated

  phpmyadmin:
    image: "phpmyadmin:fpm-alpine"
    container_name: "${APP_NAME:-laravel}-phpmyadmin"
    restart: unless-stopped
    command: cmd.sh
    environment:
      APP_NAME: ${APP_NAME:-laravel}
      PHP_MY_ADMIN: ${PHP_MY_ADMIN:-true}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      PMA_HOST: db
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 25s
    volumes:
      - phpmyadmin:/var/www/html
      - ./docker/phpmyadmin/cmd.sh:/usr/local/bin/cmd.sh:ro
      - ./:/var/www/app:delegated
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/phpmyadmin/healthcheck.sh:/usr/local/bin/healthcheck.sh:ro
    depends_on:
      db:
        condition: service_healthy
    
  cron:
    pull_policy: never
    image: "${APP_NAME:-laravel}:cron"
    container_name: "${APP_NAME:-laravel}-cron"
    restart: unless-stopped
    working_dir: /var/www/html
    build:
      context: docker
      dockerfile: cron/Dockerfile
      args:
        IMAGE: ${APP_NAME:-laravel}:php
    volumes:
      - ./docker/cron/cmd.sh:/usr/local/bin/cmd.sh:ro
      - ./docker/cron/jobs:/tmp/jobs:ro
      - ./:/var/www/html:delegated
    depends_on:
      db:
        condition: service_healthy

  node:
    pull_policy: never
    image: "${APP_NAME:-laravel}:node"
    container_name: "${APP_NAME:-laravel}-node"
    restart: never
    working_dir: /var/www/html
    profiles:
      - tools
    build:
      context: docker
      dockerfile: node/Dockerfile
      args:
        <<: *uid_gid
        NODE_VERSION: ${NODE_VERSION:-current}
    ports:
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/node/update-vite-config.sh:/usr/local/bin/update-vite-config.sh:ro

  composer:
    pull_policy: never
    image: "${APP_NAME:-laravel}:composer"
    container_name: "${APP_NAME:-laravel}-composer"
    restart: never
    working_dir: /var/www/html
    profiles:
      - tools
    build:
      context: docker
      dockerfile: composer/Dockerfile
      args:
        IMAGE: ${APP_NAME:-laravel}:php
    volumes:
      - ./docker/composer/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./:/var/www/html:delegated

  artisan:
    user: www-data
    pull_policy: never
    image: "${APP_NAME:-laravel}:php"
    container_name: "${APP_NAME:-laravel}-artisan"
    restart: never
    working_dir: /var/www/html
    entrypoint: ["entrypoint.sh"]
    profiles:
      - tools
    volumes:
      - ./docker/artisan/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./:/var/www/html:delegated
    depends_on:
      db:
        condition: service_healthy